food/urls.py
from django.urls import path

from . import views

app_name = 'food'

urlpatterns = [
    path('pizza', views.pizza, name='pizza'),
    path('burgers', views.burgers, name='burgers'),
    path('order', views.order, name='order'),
    path('success', views.success, name='success'),
    path('signup', views.signup, name='signup'),
    path('login', views.logIn, name='login'),
    path('logout', views.logOut, name='logout'),
]

gerzen_food/urls.py
from django.contrib import admin
from django.urls import path, include

from food import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('food/', include('food.urls', namespace='food')),

]

food/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Pizza(models.Model):
    name    = models.CharField(max_length=120)
    priceM  = models.DecimalField(decimal_places=2, max_digits=4)
    priceL  = models.DecimalField(decimal_places=2, max_digits=4)
    pImage  = models.URLField()

    def __str__(self):
        model_name = self.__class__.__name__
        fields_str = ", ".join((f"{field.name}={getattr(self, field.name)}" for field in self._meta.fields))
        return f"{model_name}({fields_str})"

class Burger(models.Model):
    name    = models.CharField(max_length=120)
    priceM  = models.DecimalField(decimal_places=2, max_digits=4)
    priceL  = models.DecimalField(decimal_places=2, max_digits=4)
    bImage  = models.URLField()

    def __str__(self):
        model_name = self.__class__.__name__
        fields_str = ", ".join((f"{field.name}={getattr(self, field.name)}" for field in self._meta.fields))
        return f"{model_name}({fields_str})"


class Order(models.Model):
    customer    = models.ForeignKey(User, on_delete=models.CASCADE)
    number      = models.CharField(max_length=60)
    bill        = models.DecimalField(decimal_places=2, max_digits=4)
    date        = models.DateTimeField(auto_now_add=True, blank=True)
    note        = models.TextField(blank=True, null=True)

    def __str__(self):
        model_name = self.__class__.__name__
        fields_str = ", ".join((f"{field.name}={getattr(self, field.name)}" for field in self._meta.fields))
        return f"{model_name}({fields_str})"

class Item(models.Model):
    order   = models.ForeignKey(Order, on_delete=models.CASCADE)
    name    = models.CharField(max_length=120)
    price   = models.DecimalField(max_digits=4, decimal_places=2)
    size    = models.CharField(max_length=60)

    def __str__(self):
        model_name = self.__class__.__name__
        fields_str = ", ".join((f"{field.name}={getattr(self, field.name)}" for field in self._meta.fields))
        return f"{model_name}({fields_str})"

food/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    email = forms.EmailField(max_length=100, required=True, help_text='Inform a valid Email address')
    class Meta:
        model  = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import Pizza, Burger, Order, Item
from .forms import NewUserForm
import json
import secrets

def randomOrderNumber(length):
    sample = 'ABCDEFGH0123456789'
    numberO = ''.join(secrets.SystemRandom().choice(sample) for i in range(length))
    return numberO

# Create your views here.

def index(request):
    request.session.set_expiry(0)
    # print(request.session['order'])
    ctx = {
        'active_link': 'index'
    }
    return render(request, 'food/index.html', ctx)

def pizza(request):
    request.session.set_expiry(0)
    pizzas = Pizza.objects.all()
    context = {
        'pizzas': pizzas,
        'active_link': 'pizza'
    }
    return render(request, 'food/pizza.html', context)

def burgers(request):
    request.session.set_expiry(0)
    burgers = Burger.objects.all()
    context = {
        'burgers': burgers,
        'active_link': 'burger'
    }
    return render(request, 'food/burgers.html', context)


@csrf_exempt
def order(request):
    request.session.set_expiry(0)
    if request.is_ajax():
        request.session['note'] = request.POST.get('note')
        request.session['order'] = request.POST.get('orders')
        orders = json.loads(request.session['order'])
        request.session['bill'] = request.POST.get('bill')
        randomNum = randomOrderNumber(6)

        while Order.objects.filter(number=randomNum).count()>0:
            randomNum = randomOrderNumber(6)

        if request.user.is_authenticated:
            order = Order(
                customer = request.user,
                number = randomNum,
                bill = float(request.session['bill']),
                note = request.session['note']
            )
            order.save()

            request.session['orderNum'] = order.number
            for article in orders:
                item = Item(
                    order = order,
                    name = article[0],
                    price = float(article[2]),
                    size = article[1]
                )
                item.save()
    ctx = {
        'active_link': 'order'
    }
    return render(request, 'food/order.html', ctx)


def success(request):
    orderNum = request.session['orderNum']
    bill = request.session['bill']
    items = Item.objects.filter(order__number=orderNum)
    ctx = {
        'orderNum': orderNum,
        'bill': bill,
        'items': items
    }
    return render(request, 'food/success.html', ctx)


def signup(request):
    ctx = {}
    if request.POST:
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            ctx['form'] = form
    else:
        form = NewUserForm()
        ctx['form'] = form
    return render(request, 'food/signup.html', ctx)


def logIn(request):
    if request.POST:
        username = request.POST.get('username')
        pwd = request.POST.get('password')
        user = authenticate(request, username=username, password=pwd)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.info(request, 'username and/or password are incorrect')
    ctx = {
        'active_link': 'login'
    }
    return render(request, 'food/login.html', ctx)

def logOut(request):
    logout(request)
    return redirect('index')

food/templates/food/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock title %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="icon" type="image/png" href="https://img.icons8.com/cotton/64/000000/beefburger.png">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'food/css/style.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <!-- Brand/logo -->
      <a class="navbar-brand" href="{% url 'index' %}">
        <img src="https://img.icons8.com/cotton/64/000000/beefburger.png" class='logo'/>
      </a>

      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target='#mynav' aria-controls="mynav">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="mynav">
        <!-- Links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% if active_link == 'index' %}active{% endif %}" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if active_link == 'pizza' %}active{% endif %}" href="{% url 'food:pizza' %}">Pizzas</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if active_link == 'burger' %}active{% endif %}" href="{% url 'food:burgers' %}">Burgers</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto mt-3">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <h5 class="text-light pt-3 pr-4">Welcome {{ user.username }}</h5>
            </li>
          {% endif %}
          <li class="nav-item">
            <a href="{% url 'food:order' %}" class="nav-link mt-3 {% if active_link == 'order' %}active{% endif %}"><img src="https://res.cloudinary.com/dbpredefy/image/upload/v1604573941/icons8-buying-30_gdzzrz.png"/><span id='cart'></span></a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'food:logout' %}" class="nav-link"><img class="ml-1" src='https://res.cloudinary.com/dbpredefy/image/upload/v1604574060/icons8-male-user-32_oq3wyh.png'><br>LogOut</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a href="{% url 'food:login' %}" class="nav-link {% if active_link == 'login' %}active{% endif %}"><img class="ml-1" src='https://res.cloudinary.com/dbpredefy/image/upload/v1604574060/icons8-male-user-32_oq3wyh.png'><br>LogIn</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </div>
    <div>
      {% block content %}{% endblock %}
    </div>

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script src="{% static 'food/js/main.js' %}"></script>

  </body>
</html>

food/templates/food/burgers.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %} Burgers {% endblock title %}

{% block content %}

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 text-center">
        <h2 class='title'>Our Burgers</h2>
        <div class="row">
          {% for burger in burgers %}
            <div class="col-md-4 p-4">
              <img class="picture" src="{{ burger.bImage }}">
              <h4 class="pt-3" id="bur{{ burger.id }}">{{ burger.name }}</h4>
              <div class="form-check-inline">
                <label class="form-check-label">
                  <input type="radio" name='burger{{ burger.id }}' value="{{ burger.priceM }}" class='form-check-input' checked>
                  M: ${{ burger.priceM }}
                </label>
              </div>
              <div class="form-check-inline">
                <label class="form-check-label">
                  <input type="radio" name='burger{{ burger.id }}' value="{{ burger.priceL }}" class='form-check-input'>
                  L: ${{ burger.priceL }}
                </label>
              </div>
              <div>
                <button class="btn-info mt-3" onclick="addBurger('{{ burger.id }}')">Add to cart</button>
              </div>

            </div>
          {% endfor %}
        </div>
      </div>
      <div class="col-md-4 orders">
        <div class="bg-dark p-4 rounded text-light">
          <h2 class="text-center">Order List</h2>
          <ul id="bcart"></ul>
          <h4 class="text-right" id="btotal">Total: $ 0</h4>
        </div>
      </div>
    </div>
  </div>
  <script src="{% static 'food/js/borders.js' %}"></script>


{% endblock content %}

food/templates/food/index.html
{% extends 'food/base.html' %}

{% block title %} Home {% endblock %}

{% block content %}

  <div class="home"></div>

{% endblock %}

food/templates/food/login.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %} LogIn {% endblock title %}

{% block content %}
  <div class="container-fluid p-5">
    <div class="row">
      <div class="col-md-3">

      </div>
      <div class="col-md-6 p-5 bg-dark text-light text-center">
        <h3>Log-In</h3>
        <a href="{% url 'food:signup' %}">Sign-Up</a>
        <form method="post"  class="pt-2">
          {% csrf_token %}

          <div class="form-group">
            <input type="text" name="username" placeholder="Username">
          </div>
          <div class="form-group">
            <input type="password" name="password" placeholder="*******">
          </div>
          <button type="submit" class="btn-info">LogIn</button>
          {% if messages %}
            <ul class="pt-2 text-center">
              {% for msg in messages %}
                <li style="color:red;">{{ msg }}</li>
              {% endfor %}
            </ul>
          {% endif %}
        </form>
      </div>
      <div class="col-md-3">

      </div>
    </div>
  </div>
{% endblock %}

food/templates/food/order.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %} Order {% endblock title %}

{% block content %}

  <div class="container-fluid m-4">
    {% if user.is_authenticated %}
      <h2>Welcome {{ user.username }}</h2>
    {% endif %}
    <div class="row">
      <div class="col-md-7 text-center">
        <h2>Order</h2>
        <div class="row">
          <div class="col-md-3" id="name" >
            <h3>Name</h3>
          </div>
          <div class="col-md-3" id="size">
            <h3>Size</h3>
          </div>
          <div class="col-md-3" id="price">
            <h3>Price</h3>
          </div>
          <div class="col-md-1" id="rm">

          </div>
        </div>
        <h2 id="total">Total: </h2>
      </div>

        <div class="col-md-5 mt-4">
          <h2>Message</h2>
          <textarea name="message" rows="5" cols="40" id="message"></textarea>
          <div class="ml-auto m-4">
          {% if user.is_authenticated %}
            <button type="submit" class="btn-success" onclick="order()" >Submit</button>
          </div>
        </div>
          {% else %}
        <div class="ml-auto m-4">
          <a href="{% url 'food:login' %}">LogIn</a>
        </div>
          {% endif %}
    </div>

  </div>
  <script src="{% static 'food/js/cart.js' %}">

  </script>
{% endblock %}

food/templates/food/pizza.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %} Pizzas {% endblock title %}

{% block content %}

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 text-center">
        <h2 class='title'>Our Pizzas</h2>
        <div class="row">
          {% for pizza in pizzas %}
            <div class="col-md-4 p-4">
              <img class="picture" src="{{ pizza.pImage }}">
              <h4 class="pt-3" id="piz{{ pizza.id }}">{{ pizza.name }}</h4>
              <div class="form-check-inline">
                <label class="form-check-label">
                  <input type="radio" class='form-check-input' name="pizza{{ pizza.id }}" value="{{ pizza.priceM }}" checked>
                  M: ${{ pizza.priceM }}
                </label>
              </div>
              <div class="form-check-inline">
                <label class="form-check-label">
                  <input type="radio" name="pizza{{ pizza.id }}" value="{{ pizza.priceL }}" class='form-check-input'>
                  L: ${{ pizza.priceL }}
                </label>
              </div>
              <div>
                <button class="btn-info mt-3" onclick="addPizza('{{ pizza.id }}')">Add to cart</button>
              </div>

            </div>
          {% endfor %}
        </div>
      </div>
      <div class="col-md-4 orders">
        <div class="bg-dark p-4 rounded text-light">
          <h2 class="text-center">Order List</h2>
          <ul id="pcart"></ul>
          <h4 class="text-right" id="ptotal">Total: $ 0</h4>
        </div>
      </div>
    </div>
  </div>
  <script src="{% static 'food/js/order.js' %}"></script>



{% endblock content %}

food/templates/food/signup.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %} SignUp {% endblock title %}

{% block content %}
  <div class="container-fluid p-5">
    <div class="row">
      <div class="col-md-3">

      </div>
      <div class="col-md-6 p-5 bg-dark text-light text-center">
        <h3>Sign-Up</h3>
        <a href="{% url 'food:login' %}" class="p-2">Log-In</a>
        <form method="post">
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group">
              <div>
                {{ field.label_tag }}
              </div>
              <div>
                {{ field }}
              </div>
              {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
              {% endif %}
            </div>
          {% endfor %}
          {% for error in form.errors %}
            <small style="color: red">{{ field.help_text }}</small>
          {% endfor %}
          <button type="submit" class="btn-info">SignUp</button>
        </form>
      </div>
      <div class="col-md-3">

      </div>
    </div>
  </div>
{% endblock %}

food/templates/food/success.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %} Success {% endblock title %}

{% block content %}
  <div class="container-fluid ">
    <h2>We have received your order!</h2>
    <h4>Number of orders: {{ orderNum }}</h4>
    <h3>You have ordered:</h3>
    {% for item in items %}
      <h4>{{ item.name }} {{ item.size }} {{ item.price }}</h4>
    {% endfor %}
    <h4>Total: ${{ bill }}</h4>
    <h4>If you want to modify your order, please call us</h4>
    <h4>Phone: +355676666666</h4>
  </div>
{% endblock %}